services:
  backend:
    container_name: trans_server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # expose:
    #   - "8000"
    env_file:
      - .env
    volumes:
      - .:/app
    networks:
      - transcendance
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"
    networks:
      - transcendance

networks:
  transcendance:

volumes:
  postgres_data:
