# Generated by Django 5.0.7 on 2024-07-30 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('game_id', models.AutoField(primary_key=True, serialize=False)),
                ('game_type', models.CharField(default='regular', max_length=20)),
                ('tournament_id', models.IntegerField(default=0)),
                ('player_ids', models.JSONField(default=list)),
                ('player_names', models.JSONField(default=list)),
                ('player_x', models.JSONField(default=list)),
                ('player_y', models.JSONField(default=list)),
                ('ball_speed', models.FloatField(default=3)),
                ('ball_x', models.FloatField(default=300.0)),
                ('ball_y', models.FloatField(default=200.0)),
                ('ball_velocity_x', models.FloatField(default=3)),
                ('ball_velocity_y', models.FloatField(default=1)),
                ('ball_direction_x', models.CharField(choices=[('positive', 'negative')], default='positive', max_length=8)),
                ('ball_direction_y', models.CharField(choices=[('positive', 'negative')], default='positive', max_length=8)),
                ('start_play', models.BooleanField(default=False)),
                ('msg', models.CharField(blank=True, max_length=255)),
                ('end_play', models.BooleanField(default=False)),
                ('points', models.JSONField(default=list)),
                ('winner', models.CharField(blank=True, max_length=255)),
                ('start_time', models.IntegerField(default=1722330090)),
            ],
        ),
        migrations.CreateModel(
            name='WaitingRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players', models.JSONField(default=list)),
                ('tournament_created', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('active', models.BooleanField(default=True)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('final_created', models.BooleanField(default=False)),
                ('final', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_final', to='game.game')),
                ('semifinal1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_semifinal1', to='game.game')),
                ('semifinal2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_semifinal2', to='game.game')),
            ],
        ),
    ]
