# Generated by Django 5.0.7 on 2024-07-19 12:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_game_winner_tournament_final_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
