# Generated by Django 5.0.7 on 2024-08-05 12:45

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0068_alter_game_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='start_time',
            field=models.IntegerField(default=game.models.get_current_time),
        ),
    ]
