# Generated by Django 4.2.15 on 2024-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_appuser_email_alter_appuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='school_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
