# Generated by Django 4.2.3 on 2024-07-28 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
