services:

  elasticsearch:
    container_name: elasticsearch
    build: elasticsearch/
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      # - cluster.name=docker.cluster
      # - bootstrap.memory_lock=true
      #ressource consumption limitation
      - ES_JAVA_OPTS= "-Xms256m -Xmx256m"
    volumes:
      - els-vault:/usr/share/elasticsearch/elk-vault-shared
    ports:
      - "9200:9200"
    networks:
      - elk
    entrypoint: ["/bin/bash", "-c", "/usr/share/elasticsearch/setup.sh"]

  # kibana:
  # logstash:

networks:
  elk:

volumes:
  elk-vault: