# version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    build: elasticsearch/
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - ELASTIC_PASSWORD=changemeoupas
      - xpack.security.enabled=true
      # - cluster.name=docker.cluster
      # - bootstrap.memory_lock=true
      #ressource consumption limitation
      # - ES_JAVA_OPTS= "-Xms256m -Xmx256m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - elk
    # entrypoint: ["/bin/bash", "-c", "/usr/share/elasticsearch/setup.sh"]

  # logstash:
  logstash:
    image: docker.elastic.co/logstash/logstash:8.0.0
    container_name: logstash
    environment:
      - xpack.monitoring.elasticsearch.username=elastic
      - xpack.monitoring.elasticsearch.password=changemeoupas
      - xpack.monitoring.elasticsearch.hosts=http://elasticsearch:9200
    volumes:
      - ./logstash-config:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"

  # kibana:
  kibana:
    # image: docker.elastic.co/kibana/kibana:8.12.0
    build: kibana/
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      # - ELASTICSEARCH_USERNAME=kibana_user
      # - ELASTICSEARCH_PASSWORD=changemeoupas
    # volumes:
      # - ./setup.sh:/usr/local/bin/setup.sh
      # - ./wait-for-it.sh:/usr/share/wait-for-it.sh
    # entrypoint: ["/usr/local/bin/setup.sh"]
    ports:
      - "5601:5601"
    networks:
      - elk

networks:
  elk:

volumes:
  es-data: