# Generated by Django 4.2.3 on 2024-07-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0002_user_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfileUploadView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rest.user')),
            ],
        ),
    ]
