# Generated by Django 4.2.3 on 2024-07-26 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0003_userprofileuploadview'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='UserProfileUploadView',
        ),
    ]
