# Generated by Django 4.2.3 on 2024-07-27 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest', '0004_user_username_delete_userprofileuploadview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_password',
        ),
    ]
